### ISSUE TITLE
CP

### ISSUE THREAD

**Issue by Gianlz** [Kinuzo/valorant-arduino-aimbot#6]
Podia implementar algo de verdade nesse código, ao invés de fazer uma copypasta e falar que é seu.

**Comment by Kinuzo** [comment]
?
O código faz exatamente o que e dito no projeto de forma mais otimizada e sem bugs o possível e estou atualmente 3 meses sem tomar nenhum tipo de banimento e meu elo atual e immortal, agora se você prefere continuar igual um pateta vendendo/apoiando quem ta vendendo algo publico da internet que você encontra no uc ai ja e com você irmão.

**Comment by Gianlz** [comment]
Maluco eu e o GM que criamos esse código no UC, tu simplesmente copiou ele,
igualzinho e ainda fala que otimizou kkkkk, tinha que ser só front end msm.

Em seg., 26 de set. de 2022 06:46, Kinuzo ***@***.***>
escreveu:

**Comment by Kinuzo** [comment]
Não faço a minima ideia de quem e você, muito menos de quem e GM.
Mas esse codigo se diferencia e muito do codigo bugado que vi na UC, a começar pelo fato do meu não usar o Y que deixa o aimbot todo bugado mirando pro ceu aleatoriamente e fazendo alguns absurdos, e olha que não to falando da boca pra fora, eu testei, se você quiser continuar se doendo sinta-se a vontade mas fique sabendo que nesse exato momento enquanto você ta vindo aqui falar merda varios retardados estão vendendo isso igual fizeram com o meu [Trigger em lua](https://github.com/Kinuzo/val-triggerbot-in-lua) e por essa razão postei aqui pra mais pessoas terem conhecimento disso e não gastarem seu dinheiro atoa com algo que podem encontrar na internet.

**Comment by Kinuzo** [comment]
Segue abaixo um dos exemplos em relação as pessoas que estão vendendo isso e tentando faturar em cima de algo público.

[Vídeo](https://www.youtube.com/watch?v=l3dEFboUDF4)

Além desse tem muitos outros mas sinceramente so respondi mesmo pra mostrar, pois do jeito que você veio aqui apenas pra falar merda eu deveria apenas te ignorar...

**Comment by Gianlz** [comment]
mirando pro céu kkkkkkkkk, isso é falta de conhecimento e de não saber fazer um hid decente pra arduino.

**Comment by Kinuzo** [comment]
???
cara não e possível o que estou lendo, se você ta se doendo tanto assim me manda o link da thread da uc que eu posso linkar no repositório assim o pessoal pode ir la ver ja que você ta chorando tanto.
