### ISSUE TITLE
Mouse doesnt move to the correct player postion 

### ISSUE THREAD

**Issue by iHafez** [Kinuzo/valorant-arduino-aimbot#7]
As the title says, my fov 60 and speed 0.5

https://user-images.githubusercontent.com/82477000/193463538-c9073fc2-7b46-4cdd-aaa9-4e2b36f50abd.mp4

**Comment by Kinuzo** [comment]
show me the changes you did in the code

**Comment by Kinuzo** [comment]
have you tested with leftclick?
