### ISSUE TITLE
didn't aim correctly, shaking

### ISSUE THREAD

**Issue by alienjawa25** [Kinuzo/valorant-arduino-aimbot#9]
the aim not correctly on the right place and shaking camera

**Comment by alienjawa25** [comment]
add me on discord Mellvn#3270

**Comment by alienjawa25** [comment]
error issue.
![Uploading Screenshot_6.jpg…]()

**Comment by Kinuzo** [comment]
try 50 fov and 0.5 speed

**Comment by alienjawa25** [comment]
i tried 50 fov and 0.5 speed
the aim goes up of the head

**Comment by Kinuzo** [comment]
accept
